### PR TITLE
Fix Other Sub Null State Issue for FCM token storage

### LINKED ISSUE #156: Fix Optional Sub Null State Error

### PR DESCRIPTION
**Pull request by abhibhaw**
Fixes #156

### CODE REVIEW

**Comment by DesignrKnight** [comment]
@Thesmader @Chinmay-KB 
Can you review?

**Comment by DesignrKnight** [comment]
Detailing the PR
The optional subscription to receive non-academic notification is set in login flow and for existing users, the flow gets skipped as they are already logged in. This patch is to fix that

**Comment by Chinmay-KB** [comment]
I would recommend a easier way out.

If someone wants to receive non academic notifications, why don't just subscribe them to a non acad notification topic?
Likewise when they switch it off, you subscribe

That's the most straightforward way

**Comment by abhibhaw** [comment]
We also have to save devToken na: #86

**Comment by Chinmay-KB** [comment]
Is it serving any purpose?

**Comment by abhibhaw** [comment]
They want to send customized notification in future

**Comment by DesignrKnight** [comment]
@Chinmay-KB @abhibhaw 
Merge ready?

**Comment by abhibhaw** [comment]
No one reviewed it yet!

File: scp/lib/drawer_screens/settings.dart [hunk 1]
```diff
@@ -71,6 +71,8 @@ class _SettingsState extends State<Settings> {
   Future fetchUserData(BuildContext context) async {
     SharedPreferences prefs = await SharedPreferences.getInstance();
     phoneNo = prefs.getString('phone_no');
+    username = prefs.getString('username');
+    rollNo = prefs.getString('roll_no');
     DocumentSnapshot qn =
         await Firestore.instance.collection('tokens').document(phoneNo).get();
     state = await qn.data['optionalSub'];
```
Comment (Chinmay-KB) [inline scp/lib/drawer_screens/settings.dart:78]: state is set in fetchUserdata, while state is being checked for null and set true in the initstate. Initstate fires up before fetchUserData function. You sure this is your flow because it looks like it may be prone to error

**Review by Chinmay-KB — APPROVED** [review]

**Review by DesignrKnight — APPROVED** [review]
